### ISSUE TITLE
Alexa doorbell

### ISSUE THREAD

**Issue by Watanakas** [UbhiTS/ad-alexadoorbell#1]
I can't get the AppDaemon to work,
the apps.yaml configuration is as follows:

alexa_doorbell:
    module: alexa_doorbell
    class: AlexaDoorbell
    door:
        motion_sensor: binary_sensor.main_door_motion
    home:
        alexa: media_player.salon_alexa

I have installed the custom-components alexa_media_player integration
I think it works correctly with announce, tts ...
I get that alexa gives the message, but with AppDeamon, doorbell
nothing is heard.

**Comment by UbhiTS** [comment]
I've checked your configuration and it's working on my end. I think either your motion sensor is not triggering the app, or your alexa media player is not setup. Can you please send me your AppDaemon logs so we can fix the issue.

**Comment by Watanakas** [comment]
Thanks for your quick reply, forgive my ignorance, where I get the AppDaemon records?

**Comment by UbhiTS** [comment]
Supervisor > Dashboard > AppDaemon4 > Logs

**Comment by Watanakas** [comment]
I have never used AppDaemon4
this is the log;

2020-05-11 23:59:48.806139 INFO alexa_doorbell: OUTSIDE TIME RANGE
2020-05-11 23:58:10.780383 INFO alexa_doorbell: INITIALIZED: Start 07:30:00, End 01:59:59
2020-05-11 23:58:10.757541 INFO AppDaemon: Initializing app alexa_doorbell using class AlexaDoorbell from module alexa_doorbell
2020-05-11 23:58:10.752395 INFO AppDaemon: Terminating alexa_doorbell
2020-05-11 23:58:10.739354 INFO AppDaemon: Found 1 total apps
2020-05-11 23:58:10.738137 INFO AppDaemon: App 'alexa_doorbell' changed
2020-05-11 23:58:10.736767 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-05-11 23:58:10.710217 INFO AppDaemon: Reading config

**Comment by UbhiTS** [comment]
try adding the below to the apps.yaml
```yaml
alexa_doorbell:
    module: alexa_doorbell
    class: AlexaDoorbell
    door:
        motion_sensor: binary_sensor.main_door_motion
    home:
        alexa: media_player.salon_alexa
    time:
        start: "07:00:00"
        end: "22:00:00"
```
